/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VagasRouteImport } from './routes/vagas'
import { Route as MeuCurriculoRouteImport } from './routes/meu-curriculo'
import { Route as CurriculosRouteImport } from './routes/curriculos'
import { Route as ComoFuncionaRouteImport } from './routes/como-funciona'
import { Route as AnaliseRouteImport } from './routes/analise'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ResultadoIdRouteImport } from './routes/resultado.$id'

const VagasRoute = VagasRouteImport.update({
  id: '/vagas',
  path: '/vagas',
  getParentRoute: () => rootRouteImport,
} as any)
const MeuCurriculoRoute = MeuCurriculoRouteImport.update({
  id: '/meu-curriculo',
  path: '/meu-curriculo',
  getParentRoute: () => rootRouteImport,
} as any)
const CurriculosRoute = CurriculosRouteImport.update({
  id: '/curriculos',
  path: '/curriculos',
  getParentRoute: () => rootRouteImport,
} as any)
const ComoFuncionaRoute = ComoFuncionaRouteImport.update({
  id: '/como-funciona',
  path: '/como-funciona',
  getParentRoute: () => rootRouteImport,
} as any)
const AnaliseRoute = AnaliseRouteImport.update({
  id: '/analise',
  path: '/analise',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ResultadoIdRoute = ResultadoIdRouteImport.update({
  id: '/resultado/$id',
  path: '/resultado/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/analise': typeof AnaliseRoute
  '/como-funciona': typeof ComoFuncionaRoute
  '/curriculos': typeof CurriculosRoute
  '/meu-curriculo': typeof MeuCurriculoRoute
  '/vagas': typeof VagasRoute
  '/resultado/$id': typeof ResultadoIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/analise': typeof AnaliseRoute
  '/como-funciona': typeof ComoFuncionaRoute
  '/curriculos': typeof CurriculosRoute
  '/meu-curriculo': typeof MeuCurriculoRoute
  '/vagas': typeof VagasRoute
  '/resultado/$id': typeof ResultadoIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/analise': typeof AnaliseRoute
  '/como-funciona': typeof ComoFuncionaRoute
  '/curriculos': typeof CurriculosRoute
  '/meu-curriculo': typeof MeuCurriculoRoute
  '/vagas': typeof VagasRoute
  '/resultado/$id': typeof ResultadoIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/analise'
    | '/como-funciona'
    | '/curriculos'
    | '/meu-curriculo'
    | '/vagas'
    | '/resultado/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/analise'
    | '/como-funciona'
    | '/curriculos'
    | '/meu-curriculo'
    | '/vagas'
    | '/resultado/$id'
  id:
    | '__root__'
    | '/'
    | '/analise'
    | '/como-funciona'
    | '/curriculos'
    | '/meu-curriculo'
    | '/vagas'
    | '/resultado/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AnaliseRoute: typeof AnaliseRoute
  ComoFuncionaRoute: typeof ComoFuncionaRoute
  CurriculosRoute: typeof CurriculosRoute
  MeuCurriculoRoute: typeof MeuCurriculoRoute
  VagasRoute: typeof VagasRoute
  ResultadoIdRoute: typeof ResultadoIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/vagas': {
      id: '/vagas'
      path: '/vagas'
      fullPath: '/vagas'
      preLoaderRoute: typeof VagasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/meu-curriculo': {
      id: '/meu-curriculo'
      path: '/meu-curriculo'
      fullPath: '/meu-curriculo'
      preLoaderRoute: typeof MeuCurriculoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/curriculos': {
      id: '/curriculos'
      path: '/curriculos'
      fullPath: '/curriculos'
      preLoaderRoute: typeof CurriculosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/como-funciona': {
      id: '/como-funciona'
      path: '/como-funciona'
      fullPath: '/como-funciona'
      preLoaderRoute: typeof ComoFuncionaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analise': {
      id: '/analise'
      path: '/analise'
      fullPath: '/analise'
      preLoaderRoute: typeof AnaliseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/resultado/$id': {
      id: '/resultado/$id'
      path: '/resultado/$id'
      fullPath: '/resultado/$id'
      preLoaderRoute: typeof ResultadoIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AnaliseRoute: AnaliseRoute,
  ComoFuncionaRoute: ComoFuncionaRoute,
  CurriculosRoute: CurriculosRoute,
  MeuCurriculoRoute: MeuCurriculoRoute,
  VagasRoute: VagasRoute,
  ResultadoIdRoute: ResultadoIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
