/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VagasRouteImport } from './routes/vagas'
import { Route as PainelRouteImport } from './routes/painel'
import { Route as MeuCurriculoRouteImport } from './routes/meu-curriculo'
import { Route as EvolucaoRouteImport } from './routes/evolucao'
import { Route as CurriculosRouteImport } from './routes/curriculos'
import { Route as ComoFuncionaRouteImport } from './routes/como-funciona'
import { Route as AnaliseRouteImport } from './routes/analise'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ResultadoIdRouteImport } from './routes/resultado.$id'
import { Route as EntrevistaNovaRouteImport } from './routes/entrevista.nova'
import { Route as EntrevistaIdRouteImport } from './routes/entrevista.$id'
import { Route as EntrevistaIdRelatorioRouteImport } from './routes/entrevista.$id.relatorio'

const VagasRoute = VagasRouteImport.update({
  id: '/vagas',
  path: '/vagas',
  getParentRoute: () => rootRouteImport,
} as any)
const PainelRoute = PainelRouteImport.update({
  id: '/painel',
  path: '/painel',
  getParentRoute: () => rootRouteImport,
} as any)
const MeuCurriculoRoute = MeuCurriculoRouteImport.update({
  id: '/meu-curriculo',
  path: '/meu-curriculo',
  getParentRoute: () => rootRouteImport,
} as any)
const EvolucaoRoute = EvolucaoRouteImport.update({
  id: '/evolucao',
  path: '/evolucao',
  getParentRoute: () => rootRouteImport,
} as any)
const CurriculosRoute = CurriculosRouteImport.update({
  id: '/curriculos',
  path: '/curriculos',
  getParentRoute: () => rootRouteImport,
} as any)
const ComoFuncionaRoute = ComoFuncionaRouteImport.update({
  id: '/como-funciona',
  path: '/como-funciona',
  getParentRoute: () => rootRouteImport,
} as any)
const AnaliseRoute = AnaliseRouteImport.update({
  id: '/analise',
  path: '/analise',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ResultadoIdRoute = ResultadoIdRouteImport.update({
  id: '/resultado/$id',
  path: '/resultado/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const EntrevistaNovaRoute = EntrevistaNovaRouteImport.update({
  id: '/entrevista/nova',
  path: '/entrevista/nova',
  getParentRoute: () => rootRouteImport,
} as any)
const EntrevistaIdRoute = EntrevistaIdRouteImport.update({
  id: '/entrevista/$id',
  path: '/entrevista/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const EntrevistaIdRelatorioRoute = EntrevistaIdRelatorioRouteImport.update({
  id: '/relatorio',
  path: '/relatorio',
  getParentRoute: () => EntrevistaIdRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/analise': typeof AnaliseRoute
  '/como-funciona': typeof ComoFuncionaRoute
  '/curriculos': typeof CurriculosRoute
  '/evolucao': typeof EvolucaoRoute
  '/meu-curriculo': typeof MeuCurriculoRoute
  '/painel': typeof PainelRoute
  '/vagas': typeof VagasRoute
  '/entrevista/$id': typeof EntrevistaIdRouteWithChildren
  '/entrevista/nova': typeof EntrevistaNovaRoute
  '/resultado/$id': typeof ResultadoIdRoute
  '/entrevista/$id/relatorio': typeof EntrevistaIdRelatorioRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/analise': typeof AnaliseRoute
  '/como-funciona': typeof ComoFuncionaRoute
  '/curriculos': typeof CurriculosRoute
  '/evolucao': typeof EvolucaoRoute
  '/meu-curriculo': typeof MeuCurriculoRoute
  '/painel': typeof PainelRoute
  '/vagas': typeof VagasRoute
  '/entrevista/$id': typeof EntrevistaIdRouteWithChildren
  '/entrevista/nova': typeof EntrevistaNovaRoute
  '/resultado/$id': typeof ResultadoIdRoute
  '/entrevista/$id/relatorio': typeof EntrevistaIdRelatorioRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/analise': typeof AnaliseRoute
  '/como-funciona': typeof ComoFuncionaRoute
  '/curriculos': typeof CurriculosRoute
  '/evolucao': typeof EvolucaoRoute
  '/meu-curriculo': typeof MeuCurriculoRoute
  '/painel': typeof PainelRoute
  '/vagas': typeof VagasRoute
  '/entrevista/$id': typeof EntrevistaIdRouteWithChildren
  '/entrevista/nova': typeof EntrevistaNovaRoute
  '/resultado/$id': typeof ResultadoIdRoute
  '/entrevista/$id/relatorio': typeof EntrevistaIdRelatorioRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/analise'
    | '/como-funciona'
    | '/curriculos'
    | '/evolucao'
    | '/meu-curriculo'
    | '/painel'
    | '/vagas'
    | '/entrevista/$id'
    | '/entrevista/nova'
    | '/resultado/$id'
    | '/entrevista/$id/relatorio'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/analise'
    | '/como-funciona'
    | '/curriculos'
    | '/evolucao'
    | '/meu-curriculo'
    | '/painel'
    | '/vagas'
    | '/entrevista/$id'
    | '/entrevista/nova'
    | '/resultado/$id'
    | '/entrevista/$id/relatorio'
  id:
    | '__root__'
    | '/'
    | '/analise'
    | '/como-funciona'
    | '/curriculos'
    | '/evolucao'
    | '/meu-curriculo'
    | '/painel'
    | '/vagas'
    | '/entrevista/$id'
    | '/entrevista/nova'
    | '/resultado/$id'
    | '/entrevista/$id/relatorio'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AnaliseRoute: typeof AnaliseRoute
  ComoFuncionaRoute: typeof ComoFuncionaRoute
  CurriculosRoute: typeof CurriculosRoute
  EvolucaoRoute: typeof EvolucaoRoute
  MeuCurriculoRoute: typeof MeuCurriculoRoute
  PainelRoute: typeof PainelRoute
  VagasRoute: typeof VagasRoute
  EntrevistaIdRoute: typeof EntrevistaIdRouteWithChildren
  EntrevistaNovaRoute: typeof EntrevistaNovaRoute
  ResultadoIdRoute: typeof ResultadoIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/vagas': {
      id: '/vagas'
      path: '/vagas'
      fullPath: '/vagas'
      preLoaderRoute: typeof VagasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/painel': {
      id: '/painel'
      path: '/painel'
      fullPath: '/painel'
      preLoaderRoute: typeof PainelRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/meu-curriculo': {
      id: '/meu-curriculo'
      path: '/meu-curriculo'
      fullPath: '/meu-curriculo'
      preLoaderRoute: typeof MeuCurriculoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/evolucao': {
      id: '/evolucao'
      path: '/evolucao'
      fullPath: '/evolucao'
      preLoaderRoute: typeof EvolucaoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/curriculos': {
      id: '/curriculos'
      path: '/curriculos'
      fullPath: '/curriculos'
      preLoaderRoute: typeof CurriculosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/como-funciona': {
      id: '/como-funciona'
      path: '/como-funciona'
      fullPath: '/como-funciona'
      preLoaderRoute: typeof ComoFuncionaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analise': {
      id: '/analise'
      path: '/analise'
      fullPath: '/analise'
      preLoaderRoute: typeof AnaliseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/resultado/$id': {
      id: '/resultado/$id'
      path: '/resultado/$id'
      fullPath: '/resultado/$id'
      preLoaderRoute: typeof ResultadoIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/entrevista/nova': {
      id: '/entrevista/nova'
      path: '/entrevista/nova'
      fullPath: '/entrevista/nova'
      preLoaderRoute: typeof EntrevistaNovaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/entrevista/$id': {
      id: '/entrevista/$id'
      path: '/entrevista/$id'
      fullPath: '/entrevista/$id'
      preLoaderRoute: typeof EntrevistaIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/entrevista/$id/relatorio': {
      id: '/entrevista/$id/relatorio'
      path: '/relatorio'
      fullPath: '/entrevista/$id/relatorio'
      preLoaderRoute: typeof EntrevistaIdRelatorioRouteImport
      parentRoute: typeof EntrevistaIdRoute
    }
  }
}

interface EntrevistaIdRouteChildren {
  EntrevistaIdRelatorioRoute: typeof EntrevistaIdRelatorioRoute
}

const EntrevistaIdRouteChildren: EntrevistaIdRouteChildren = {
  EntrevistaIdRelatorioRoute: EntrevistaIdRelatorioRoute,
}

const EntrevistaIdRouteWithChildren = EntrevistaIdRoute._addFileChildren(
  EntrevistaIdRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AnaliseRoute: AnaliseRoute,
  ComoFuncionaRoute: ComoFuncionaRoute,
  CurriculosRoute: CurriculosRoute,
  EvolucaoRoute: EvolucaoRoute,
  MeuCurriculoRoute: MeuCurriculoRoute,
  PainelRoute: PainelRoute,
  VagasRoute: VagasRoute,
  EntrevistaIdRoute: EntrevistaIdRouteWithChildren,
  EntrevistaNovaRoute: EntrevistaNovaRoute,
  ResultadoIdRoute: ResultadoIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
